before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: QAtuQwVFEXVgPmy27xawHygNvreWNRcBzHgnFf7dWDp9+rqGyH726bCRGdExKEUkGHH9wpQqAoN89gO0vxmdKLJWr1rycnSV8zTq4ctSPchtke1eIbTtdMYQcQ3ydqEOyR8JocauaW4kKwh45ukIclgHRAU+YHT1IktYBNVVCp31Rv6w///kvKWjQJwPboiuDd6Zhz8h6Oy7RQr3giKJU20D2IM/CCQ0F3JGuouHLCRA3XHqiayl5UTRPjjynqLFf5I25lzsCYRxy1lY1Qn5gpaxEG/fvZXM8XrTKG4cWS5DtHkrOguLWbi6oH1IUzY37JXPiVa00LMfzdxBwEdeQScoNLFfTL1K5KwH4kKQuwUNedQ8m1Z2dWDnS/ih431tn/rY9VJtJhOIpsha2Uj0gJDD8CM0qva4nhyb/zU+DqznL+kvGY/LWu4+lK8Ev4Lg+tqKxD3HROCS1JatJ4Y3naotgKhHe03Vo60NRZ4h7VoDy8C2d/D8HxygACH1kaez1/qd2TkR5B4JXtViCsnMAWAYP8A35YX+arYR4ndKIx8zKbmRk2LZ73sdAvSX7cYqni8crufoPvg2Eyc7H76u6Tou+6+szG0SWQ6J5Q/q8ok7jrKKZOMthDYWgTfl+ZbJTuTqvA70FDJvK8Y+7yEk2txh2ONu+X3GTwBGOkw2K3w= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
